"""
Django settings for huntment project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from .settings_prod import *
DEBUG = True

ALLOWED_HOSTS = ['*']

ROOT_URLCONF = 'myB2B.urls'

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': os.environ.get('DB_NAME'),
        # 'USER': os.environ.get('DB_USER'),
        # 'PASSWORD': os.environ.get('DB_PASSWORD')
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test1',
        'HOST':'localhost',
        'USER': 'root',
        'PASSWORD': '',
        'PORT': 3306,
    }
}

