# Generated by Django 4.1.1 on 2022-10-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_fullsale_uuid_alter_partialstakesale_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullsale',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partialstakesale',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
