# Generated by Django 4.1.1 on 2022-10-07 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fullsale_uuid_alter_partialstakesale_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullsale',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partialstakesale',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
