# Generated by Django 4.1.1 on 2022-10-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_fullsale_uuid_alter_partialstakesale_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullsale',
            name='brochure_doc',
        ),
        migrations.RemoveField(
            model_name='fullsale',
            name='business_proof',
        ),
        migrations.RemoveField(
            model_name='partialstakesale',
            name='brochure_doc',
        ),
        migrations.RemoveField(
            model_name='partialstakesale',
            name='business_proof',
        ),
        migrations.AlterField(
            model_name='pssimages',
            name='facility_photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PSSDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure_doc', models.FileField(blank=True, max_length=10, null=True, upload_to='')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fullsale')),
            ],
        ),
        migrations.CreateModel(
            name='PSSBusiProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_proof', models.FileField(blank=True, null=True, upload_to='')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fullsale')),
            ],
        ),
        migrations.CreateModel(
            name='FSDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure_doc', models.FileField(blank=True, max_length=10, null=True, upload_to='')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fullsale')),
            ],
        ),
        migrations.CreateModel(
            name='FSBusiProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_proof', models.FileField(blank=True, null=True, upload_to='')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fullsale')),
            ],
        ),
    ]
