# Generated by Django 4.1.1 on 2022-10-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_fullsale_brochure_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsdoc',
            name='brochure_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='FSDocu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fullsale')),
            ],
        ),
    ]
