# Generated by Django 4.1.1 on 2022-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_fsdoc_brochure_doc_fsdocu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FSDocu',
        ),
    ]
