# Generated by Django 4.1.1 on 2022-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_fsdocu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pssdoc',
            name='brochure_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
