# Generated by Django 4.1.1 on 2022-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_sellorleaseassets_sl_assetdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fullsale',
            name='interested',
            field=models.CharField(blank=True, error_messages={'required': 'Please enter your interested business.'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partialstakesale',
            name='interested',
            field=models.CharField(blank=True, error_messages={'required': 'Please enter your interested business.'}, max_length=50, null=True),
        ),
    ]
