# Generated by Django 4.1.1 on 2022-12-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_plan_fullsale_plan_partialstakesale_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
